package restaurant_simulator;

import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 * Interfaccia grafica RestaurantPreConfig, rappresenta la prima interfaccia
 * grafica che si presenta al primo avvio della modalità manager. Questa interfaccia
 * espone un introduzione alla modalità manager e come prima configurazione del software
 * prevede l'inserimento del nome del ristorante che si vuole creare.
 * 
 * @author Danilo Dolce e Simone Contini
 * @version 1.0
 */
public class RestaurantPreConfig extends javax.swing.JFrame {
    
    private final String fileRestaurantInfoPath = "data/RestaurantInfo.csv";
    private final String fileOrderPath = "data/Order.csv";
    private final String fileOrderItemPath = "data/OrderItem.csv";
    private final static String fileManagerModeDescriptionpath = "file/managerMode.txt";

    
    /**
     * Costruttore senza parametri della classe RestaurantPreConfig
     */
    public RestaurantPreConfig() {
        super("Restaurant Simulator (MM): Pre-configurazione del ristorante");
        initComponents();
        
        // Renderizza l'introduzione alla modalità manager 
        String managerModeIntro = "";
        managerModeIntro+=FileUtility.readFileToString(fileManagerModeDescriptionpath);
        this.txtAreaIntro.setText(managerModeIntro);
        
        /*** Listener ***/
        
        btnNext.addActionListener(
            ev -> {
                // Validatore base per i dati immessi nell'interfaccia grafica RestaurantPreConfig
                RestaurantPreConfigValidator validator = new RestaurantPreConfigValidator();
               
                boolean validModel = false;

                try{
                    // Ottengo il risultato della validazione
                    validModel = validator.validate(this);
                }
                catch(RestaurantConfigException e) {
                    // Stampa eventuali errori generati dalla validazione
                    JOptionPane.showMessageDialog(this, e.getMessage(), "ErrorBox", JOptionPane.ERROR_MESSAGE);
                }
                
                // Se il modello è valido passo all'interfaccia grafica ManagerHome
                if (validModel) {
                    
                    Restaurant restaurant = new Restaurant(txtRestaturantName.getText());
                    restaurant.setId(CsvUtility.maxIntegerColumn(0, fileRestaurantInfoPath)+1);
                    restaurant.addRecord();

                    // Passo al Restaurant Manager Menu
                    this.setVisible(false);
                    ManagerHome managerMenu = new ManagerHome();
                    managerMenu.setVisible(true);
                }
            });
        
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lblInsertRestaurantName = new javax.swing.JLabel();
        txtRestaturantName = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtAreaIntro = new javax.swing.JTextArea();
        btnNext = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblIcoManager = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable2);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(jTable4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(45, 52, 54));

        lblInsertRestaurantName.setFont(new java.awt.Font("Muli", 0, 14)); // NOI18N
        lblInsertRestaurantName.setForeground(new java.awt.Color(255, 255, 255));
        lblInsertRestaurantName.setText("Inserisci il nome del tuo ristorante:");

        txtRestaturantName.setText("Il mio ristorante");
        txtRestaturantName.setToolTipText("Il nome del tuo ristorante");
        txtRestaturantName.setPreferredSize(new java.awt.Dimension(82, 25));

        txtAreaIntro.setEditable(false);
        txtAreaIntro.setBackground(new java.awt.Color(45, 52, 54));
        txtAreaIntro.setColumns(20);
        txtAreaIntro.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtAreaIntro.setForeground(new java.awt.Color(255, 255, 255));
        txtAreaIntro.setRows(5);
        jScrollPane4.setViewportView(txtAreaIntro);

        btnNext.setText("Continua");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNext))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane4)
                            .addComponent(txtRestaturantName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 566, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblInsertRestaurantName)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblInsertRestaurantName)
                .addGap(11, 11, 11)
                .addComponent(txtRestaturantName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnNext)
                .addGap(20, 20, 20))
        );

        jPanel2.setBackground(new java.awt.Color(45, 52, 54));

        lblIcoManager.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIcoManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Manager.png"))); // NOI18N
        lblIcoManager.setToolTipText("Modalità Manager");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblIcoManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lblIcoManager)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Questo metodo restituisce il nome del ristorante inserito in input
     * 
     * @return il nome del ristorante inserito in input
     */
    public String getInputRestName() {
        return txtRestaturantName.getText();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurantPreConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurantPreConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurantPreConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurantPreConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurantPreConfig().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNext;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JLabel lblIcoManager;
    private javax.swing.JLabel lblInsertRestaurantName;
    private javax.swing.JTextArea txtAreaIntro;
    private javax.swing.JTextField txtRestaturantName;
    // End of variables declaration//GEN-END:variables
}
