package restaurant_simulator;

import java.io.File;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;

/**
 * Interfaccia RestaurantGeneralConfig, consente di modificare il nome del ristorante 
 * e di ritornare alle impostazioni di fabbrica del software
 * 
 * @author Danilo Dolce e Simone Contini
 * @version 1.0
 */
public class RestaurantGeneralConfig extends javax.swing.JFrame {
        
    private final static String fileRestaurantInfoPath = "data/RestaurantInfo.csv";
    private final static String fileTablePath = "data/Table.csv";
    private final static String fileCategoryPath = "data/Category.csv";
    private final static String fileProductPath = "data/Product.csv";
    private final static String fileUserPath = "data/User.csv";
    private final static String fileOrderPath = "data/Order.csv";
    private final static String fileOrderItemPath = "data/OrderItem.csv";
    private final static String fileCategoryFeedbackPath = "data/CategoryFeedback.csv";
    private final static String fileFeedbackPath = "data/Feedback.csv";
    
    private final static String fileManagerModeDescriptionpath = "file/managerMode.txt";

    
    private String restaurantName;

    /**
     * Creates new form RestaurantGeneralConfig
     */
    public RestaurantGeneralConfig() {
        super("Restaurant Simulator (MM): Impostazioni generali");
        initComponents();
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    
    /**
     * Creates new form RestaurantGeneralConfig
     */
    public RestaurantGeneralConfig(String restaurantName) {
        super("Restaurant Simulator (MM): Impostazioni generali");
        initComponents();
        this.restaurantName = restaurantName;
        this.txtRestaurantName.setText(restaurantName);
        
        btnBack.addActionListener(
            ev -> {
                ManagerHome managerMenu = new ManagerHome();
                managerMenu.setVisible(true);
                this.setVisible(false);
        });
        
        btnSave.addActionListener(
            ev -> {
                RestaurantGeneralConfigValidator validator = new RestaurantGeneralConfigValidator();

                boolean validModel = false;

                try{
                    validModel = validator.validate(this);
                }
                catch(RestaurantConfigException e) {
                    JOptionPane.showMessageDialog(this, e.getMessage(), "ErrorBox", JOptionPane.ERROR_MESSAGE);
                }

                if (validModel) {
                    List<String> dataToCsv = Arrays.asList("0", txtRestaurantName.getText());
                    // Crea il Csv contenente le informazioni base (id e nome) del ristorante
                    CsvUtility.addLineToCsv(dataToCsv, fileRestaurantInfoPath);

                    JOptionPane.showMessageDialog(this, "Salvataggio effettuato", "InfoBox", JOptionPane.INFORMATION_MESSAGE);
                }
        });
        
        btnResetSoftware.addActionListener(
            ev -> {
                int result = JOptionPane.showConfirmDialog(this, "Tutti i tuoi dati verranno cancellati: sei sicuro di voler procedere?", "WarningBox", 
                        JOptionPane.OK_OPTION, JOptionPane.WARNING_MESSAGE);

                if (result == JOptionPane.YES_OPTION) {
                    this.setVisible(false);
                    new File(fileRestaurantInfoPath).delete();
                    new File(fileTablePath).delete();
                    new File(fileCategoryPath).delete();
                    new File(fileProductPath).delete();
                    new File(fileOrderPath).delete();
                    new File(fileOrderItemPath).delete();
                    new File(fileCategoryFeedbackPath).delete();
                    new File(fileFeedbackPath).delete();
                    new File(fileUserPath).delete();
                    new File(fileManagerModeDescriptionpath).delete();

                    // Esco dal programma
                    System.exit(0); 
                }
        });
        
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    
    /**
     * Questo metodo restituisce il nome del ristorante inserito in input
     * 
     * @return il nome del ristorante inserito in input
     */
    public String getInputRestaurantName() {
        return this.txtRestaurantName.getText();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblRestaurantName = new javax.swing.JLabel();
        txtRestaurantName = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnResetSoftware = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(45, 52, 54));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/left-arrow.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.setContentAreaFilled(false);
        btnBack.setFocusPainted(false);
        btnBack.setMargin(new java.awt.Insets(2, 0, 2, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(btnBack)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(45, 52, 54));

        lblRestaurantName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblRestaurantName.setForeground(new java.awt.Color(255, 255, 255));
        lblRestaurantName.setText("Nome ristorante:");

        txtRestaurantName.setToolTipText("Modifica il nome del tuo ristorante");
        txtRestaurantName.setPreferredSize(new java.awt.Dimension(60, 25));

        btnSave.setText("Salva");

        btnResetSoftware.setText("Ripristina le impostazioni di fabbrica");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btnResetSoftware)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSave))
                    .addComponent(txtRestaurantName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblRestaurantName)
                        .addGap(0, 307, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblRestaurantName)
                .addGap(11, 11, 11)
                .addComponent(txtRestaurantName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 348, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnResetSoftware))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurantGeneralConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurantGeneralConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurantGeneralConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurantGeneralConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurantGeneralConfig().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnResetSoftware;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblRestaurantName;
    private javax.swing.JTextField txtRestaurantName;
    // End of variables declaration//GEN-END:variables
}
