package restaurant_simulator;

import javax.swing.JFrame;

/**
 * Interfaccia Grafica RestaurantManagerHome, rappresenta la Home della modalità
 * Manager
 * 
 * @author Danilo Dolce e Simone Contini
 * @version 1.0
 */
public class RestaurantManagerHome extends javax.swing.JFrame {
    
    Restaurant rest;
    
    /**
     * Costruttore senza parametri della classe RestaurantManagerHome
     */
    public RestaurantManagerHome() {
        super("Restaurant Simulator (MM): Home Manager");
        initComponents(); 
        RestaurantBuilderDirector rbd = new RestaurantBuilderDirector();
        RestaurantConcreteBuilder rcb = new RestaurantConcreteBuilder();
        rest = rbd.buildRestaurant(rcb);
        lblRestaurantName.setText(rest.getName());
        
        btnMenu.addActionListener(
            ev -> {
                ManagerMenu menuFrame = new ManagerMenu(rest.getMenu());
                this.setVisible(false);
                menuFrame.setVisible(true);
            });
        
        btnOrderHistory.addActionListener(
            ev -> {
                ManagerOrderList managerOrderList = new ManagerOrderList(this.rest);
                this.setVisible(false);
                managerOrderList.setVisible(true);
            });
        
        btnClients.addActionListener(
            ev -> {
                ManagerUserList managerUserList = new ManagerUserList(this.rest);
                this.setVisible(false);
                managerUserList.setVisible(true);
            });
        
        btnCalendary.addActionListener(
            ev -> {
                ManagerTableList managerTableList = new ManagerTableList(rest);
                this.setVisible(false);
                managerTableList.setVisible(true);
                managerTableList.toFront();
            });
        
        btnSimulator.addActionListener(
            ev -> {
                Simulator simulator = new Simulator(rest.getOrders());
                simulator.setVisible(true);
                this.setVisible(false);
            });
        
        menuGeneralSettings.addActionListener(
            ev -> {
                RestaurantGeneralConfig rc = new RestaurantGeneralConfig(rest.getName());
                rc.setVisible(true);
                this.setVisible(false);
            });
        
        menuTableSettings.addActionListener(
            ev -> {
                RestaurantTableConfig rtc = new RestaurantTableConfig(rest.getTables());
                rtc.setVisible(true);
                this.setVisible(false);
            });
        
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMenu = new javax.swing.JButton();
        btnOrderHistory = new javax.swing.JButton();
        btnCalendary = new javax.swing.JButton();
        btnClients = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblRestaurantName = new javax.swing.JLabel();
        btnSimulator = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuGeneralSettings = new javax.swing.JMenuItem();
        menuTableSettings = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(45, 52, 54));
        jPanel1.setLayout(new java.awt.GridLayout(2, 2));

        btnMenu.setForeground(new java.awt.Color(255, 255, 255));
        btnMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N
        btnMenu.setToolTipText("Menu");
        btnMenu.setBorder(null);
        btnMenu.setContentAreaFilled(false);
        btnMenu.setFocusPainted(false);
        btnMenu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(btnMenu);

        btnOrderHistory.setForeground(new java.awt.Color(255, 255, 255));
        btnOrderHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/orders.png"))); // NOI18N
        btnOrderHistory.setToolTipText("Storico ordini");
        btnOrderHistory.setContentAreaFilled(false);
        jPanel1.add(btnOrderHistory);

        btnCalendary.setForeground(new java.awt.Color(255, 255, 255));
        btnCalendary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/calendar.png"))); // NOI18N
        btnCalendary.setToolTipText("Agenda");
        btnCalendary.setBorder(null);
        btnCalendary.setContentAreaFilled(false);
        jPanel1.add(btnCalendary);

        btnClients.setForeground(new java.awt.Color(255, 255, 255));
        btnClients.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clients.png"))); // NOI18N
        btnClients.setToolTipText("Clienti");
        btnClients.setContentAreaFilled(false);
        jPanel1.add(btnClients);

        jPanel2.setBackground(new java.awt.Color(45, 52, 54));

        lblRestaurantName.setFont(new java.awt.Font("Trajan Pro", 1, 18)); // NOI18N
        lblRestaurantName.setForeground(new java.awt.Color(255, 255, 0));
        lblRestaurantName.setText("Nome ristorante");

        btnSimulator.setFont(new java.awt.Font("Muli", 0, 14)); // NOI18N
        btnSimulator.setForeground(new java.awt.Color(255, 255, 255));
        btnSimulator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/clock.png"))); // NOI18N
        btnSimulator.setToolTipText("Clicca per effettuare una simulazione");
        btnSimulator.setContentAreaFilled(false);
        btnSimulator.setFocusPainted(false);
        btnSimulator.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        btnSimulator.setLabel("Simula");
        btnSimulator.setMargin(new java.awt.Insets(2, 0, 2, 0));
        btnSimulator.setPreferredSize(new java.awt.Dimension(100, 45));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblRestaurantName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSimulator, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRestaurantName)
                    .addComponent(btnSimulator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jMenu1.setText("Impostazioni");

        menuGeneralSettings.setText("Impostazioni generali");
        jMenu1.add(menuGeneralSettings);

        menuTableSettings.setText("Impostazioni tavoli");
        jMenu1.add(menuTableSettings);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RestaurantManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RestaurantManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RestaurantManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RestaurantManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RestaurantManagerHome().setVisible(true);
                //RestaurantBuilderDirector rbd = new RestaurantBuilderDirector();

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalendary;
    private javax.swing.JButton btnClients;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnOrderHistory;
    private javax.swing.JButton btnSimulator;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblRestaurantName;
    private javax.swing.JMenuItem menuGeneralSettings;
    private javax.swing.JMenuItem menuTableSettings;
    // End of variables declaration//GEN-END:variables
}
