package restaurant_simulator;


/**
 * Interfaccia grafica UserHome, rappresenta la vista della home relativa al cliente
 * 
 * @author Danilo Dolce e Simone Contini
 * @version 1.0
 */
public class UserHome extends javax.swing.JFrame {
    
    // Il cliente loggato
    User user;

    /**
     * Costruttore senza parametri della classe UserHome
     */
    public UserHome() {
        super("Restaurant Simulator (MC): Home Cliente");
        initComponents();
        this.setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    
    /**
     * Costruttore con parametri della classe UserHome
     * 
     * @param user l'utente loggato
     */
    public UserHome(User user) {
        super("Restaurant Simulator (MC): Home Cliente");
        initComponents();
        this.user = user;
        lblWelcomeUser.setText("Benvenuto "+user.getUsername());
        
        btnMyOrder.addActionListener(
            ev -> {
                UserOrderList userOrderList = new UserOrderList(this.user);
                userOrderList.setVisible(true);
                this.dispose();
            });
        
        btnReservation.addActionListener(
            ev -> {
                RestaurantBuilderDirector rbd = new RestaurantBuilderDirector();
                RestaurantConcreteBuilder rcb = new RestaurantConcreteBuilder();
                Restaurant rest = rbd.buildRestaurant(rcb);
                UserReservation userReservation = new UserReservation(rest.getMenu(), this.user);
                userReservation.setVisible(true);
                this.dispose();
            });
        
        this.setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblWelcomeUser = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        btnReservation = new javax.swing.JButton();
        btnMyOrder = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(45, 52, 54));

        lblWelcomeUser.setFont(new java.awt.Font("Muli", 1, 14)); // NOI18N
        lblWelcomeUser.setForeground(new java.awt.Color(255, 255, 0));
        lblWelcomeUser.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblWelcomeUser.setText("Benvenuto");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblWelcomeUser, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblWelcomeUser)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(45, 52, 54));
        jPanel3.setLayout(new java.awt.GridLayout(2, 0));

        btnReservation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reservation.png"))); // NOI18N
        btnReservation.setToolTipText("Effettua prenotazione");
        btnReservation.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ordinazione", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        btnReservation.setContentAreaFilled(false);
        btnReservation.setFocusPainted(false);
        jPanel3.add(btnReservation);

        btnMyOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/user-orders.png"))); // NOI18N
        btnMyOrder.setToolTipText("I miei ordini");
        btnMyOrder.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "I miei ordini", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        btnMyOrder.setContentAreaFilled(false);
        jPanel3.add(btnMyOrder);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMyOrder;
    private javax.swing.JButton btnReservation;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblWelcomeUser;
    // End of variables declaration//GEN-END:variables
}
